---

- hosts: has_groups
  tasks:
  - name: create group media
    group:
      gid: 1001
      name: media
  - name: create group gmedia
    group:
      gid: 1002
      name: gmedia
  - name: create group austin
    group:
      gid: 1003
      name: austin
  - name: create group g
    group:
      gid: 1004
      name: g
  - name: create group wheel
    group:
      name: wheel
  - name: copy sudoers
    copy:
      src: sudoers.wheel
      dest: /opt/local/etc/sudoers.d/wheel
- hosts: has_user_austin
  tasks:
  - name: create user austin
    user:
      create_home: false
      group: austin
      groups: media,wheel
      home: /zones/home/austin
      name: austin
      shell: /usr/bin/bash
      uid: 1001
- hosts: has_user_g
  tasks:
  - name: create user g
    user:
      create_home: false
      group: g
      groups: gmedia
      home: /zones/home/g
      name: g
      shell: /usr/bin/bash
      uid: 1002


- hosts: fs
  handlers:
    - name: restart smbd
      service:
        name: smbd
        state: restarted
    - name: restart nmbd
      service:
        name: nmbd
        state: restarted
    - name: restart avahi
      service:
        name: avahi
        state: restarted
  tasks:
  - name: install samba
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: samba-4
      state: present
    notify:
      - restart smbd
      - restart nmbd
  - name: install samba
    pkgin:
      name: avahi
      state: present
  - name: copy samba config
    copy:
      src: fs/smb.conf
      dest: /opt/local/etc/samba/smb.conf
  - name: copy avahi config
    copy:
      src: fs/hosts
      dest: /opt/local/etc/avahi/hosts
    notify:
      - restart avahi
  - name: copy avahi servoces config
    copy:
      src: fs/_etc_avahi_services_samba.service
      dest: /opt/local/etc/avahi/services/_etc_avahi_services_samba.service
    notify:
      - restart avahi
  - name: enable smbd
    service:
      name: smbd
      state: started
      enabled: yes
  - name: enable nmbd
    service:
      name: nmbd
      state: started
      enabled: yes
  - name: enable avahi
    service:
      name: nmbd
      state: started
      enabled: yes

- hosts: dns
  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
  tasks:
  - name: install dnsmasq
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: dnsmasq
      state: present
    notify:
      - restart dnsmasq
  - name: hosts file
    copy:
      src: dns/hosts
      dest: /etc/hosts
    notify:
      - restart dnsmasq
  - name: copy dnsmasq config
    copy:
      src: dns/dnsmasq.conf
      dest: /opt/local/etc/dnsmasq.conf
    notify:
      - restart dnsmasq
  - name: enable dnsmasq
    service:
      name: dnsmasq
      state: started
      enabled: yes
  - name: dns update script
    copy:
      src: dns/updateDns.sh
      dest: /root/updateDns.sh
      mode: 0700
  - name: dns update cron
    cron:
      name: "dynamic DNS update"
      minute: "54"
      hour: "7"
      job: "/root/updateDns.sh"

- hosts: torrent
  handlers:
    - name: import transmission
      shell: svccfg import /opt/local/lib/svc/manifest/transmission.xml
    - name: restart transmission
      service:
        name: transmission
        state: restarted
  tasks:
  - name: install transmission
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: transmission
      state: present
    notify:
      - restart transmission
  - name: transmission smf manifest
    copy:
      src: torrent/transmission.xml
      dest: /opt/local/lib/svc/manifest/transmission.xml
    notify:
      - import transmission

- hosts: devl
  tasks:
  - name: install git
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: git
      state: present

- hosts: plex
  tasks:
  - name: update apt and transport
    apt:
      autoremove: yes
      update_cache: yes
      upgrade: 'yes'
  - name: install https support
    apt:
      name: apt-transport-https
  - name: Add the plex key
    apt_key:
      data: "{{ lookup('file', 'plex/PlexSign.key') }}"
      state: present
  - name: Install plex repo
    apt_repository:
      filename: plex
      repo: deb https://downloads.plex.tv/repo/deb public main
  - name: Install plex
    apt:
      name: plexmediaserver