---

- hosts: has_groups
  tasks:
  - name: create group media
    group:
      gid: 1001
      name: media
  - name: create group gmedia
    group:
      gid: 1002
      name: gmedia
  - name: create group wheel
    group:
      name: wheel
  - name: copy sudoers
    copy:
      src: sudoers.wheel
      dest: /opt/local/etc/sudoers.d/wheel
- hosts: has_user_austin
  tasks:
  - name: create group austin
    group:
      gid: 1003
      name: austin
  - name: create user austin
    user:
      create_home: false
      group: austin
      groups: media,wheel
      home: /zones/home/austin
      name: austin
      shell: /usr/bin/bash
      uid: 1001
- hosts: has_user_g
  tasks:
  - name: create group g
    group:
      gid: 1004
      name: g
  - name: create user g
    user:
      create_home: false
      group: g
      groups: gmedia
      home: /zones/home/g
      name: g
      shell: /usr/bin/bash
      uid: 1002


- hosts: fs
  handlers:
    - name: restart smbd
      service:
        name: smbd
        state: restarted
    - name: restart nmbd
      service:
        name: nmbd
        state: restarted
  tasks:
  - name: install samba
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: samba-4
      state: present
    notify:
      - restart smbd
      - restart nmbd
  - name: copy samba config
    copy:
      src: fs/smb.conf
      dest: /opt/local/etc/samba/smb.conf
    notify:
      - restart smbd
      - restart nmbd
  - name: enable smbd
    service:
      name: smbd
      state: started
      enabled: true
  - name: enable nmbd
    service:
      name: nmbd
      state: started
      enabled: true

- hosts: nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
  tasks:
  - name: install nginx
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: nginx
      state: present
    notify:
      - restart nginx
  - name: copy nginx config
    copy:
      src: nginx/nginx.conf
      dest: /opt/local/etc/nginx/nginx.conf
    notify:
      - restart nginx
  - name: enable nginx
    service:
      name: nginx
      state: started
      enabled: true

- hosts: dns
  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
  tasks:
  - name: install dnsmasq
    pkgin:
      update_cache: yes
      full_upgrade: yes
      name: dnsmasq
      state: present
    notify:
      - restart dnsmasq
  - name: hosts file
    copy:
      src: dns/hosts
      dest: /etc/hosts
    notify:
      - restart dnsmasq
  - name: copy dnsmasq config
    copy:
      src: dns/dnsmasq.conf
      dest: /opt/local/etc/dnsmasq.conf
    notify:
      - restart dnsmasq
  - name: enable dnsmasq
    service:
      name: dnsmasq
      state: started
      enabled: true
  - name: dns update script
    copy:
      src: dns/updateDns.sh
      dest: /root/updateDns.sh
      mode: 0700
  - name: dns update cron
    cron:
      name: "dynamic DNS update"
      minute: "54"
      hour: "7"
      job: "/root/updateDns.sh"